id: P007011
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2545
  title: བླ་མའི་ཡང་ཏིག་ལས་གཉིས་ཀའི་ཡང་ཡིག་ཀྱི་རྣམ་པར་བཤད་པ་ཉི་མའི་སྣང་བ
  author: ''
  volumes:
    e3e1fa8e986d4a9babbd31e3b7e0c9a9:
      image_group_id: I1CZ2720
      title: ''
      volume_number: 1
      total_pages: 250
ebook_metadata:
  title: བླ་མའི་ཡང་ཏིག་ལས་གཉིས་ཀའི་ཡང་ཡིག་ཀྱི་རྣམ་པར་བཤད་པ་ཉི་མའི་སྣང་བ
  author: ''
  sku: P007011
  cover: cover.jpg
  layers:
  - pagination
