id: IDA6099A5
legacy_id: P007011
ocr_import_info:
  bdrc_scan_id: W1CZ2545
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T20:33:46'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:24:00.704401+00:00'
last_modified: 2022-08-31 03:24:23.234331
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ2545
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ2545
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བླ་མའི་ཡང་ཏིག་ལས་གཉིས་ཀའི་ཡང་ཡིག་ཀྱི་རྣམ་པར་བཤད་པ་ཉི་མའི་སྣང་བ།
  author: མཁན་པོ་ངག་དགའ
statistics:
  ocr_word_mean_confidence_index: 0.5298948480503797
  ocr_word_median_confidence_index: 0.5
quality: null
bases:
  I1CZ2720:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2720
      total_pages: 250
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2720.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5298948480503797
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
