id: IDA6099A5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T20:35:13+00:00'
last_modified: '2022-06-08T11:58:10.038198+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2545
  title: བླ་མའི་ཡང་ཏིག་ལས་གཉིས་ཀའི་ཡང་ཡིག་ཀྱི་རྣམ་པར་བཤད་པ་ཉི་མའི་སྣང་བ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    FFFC:
      image_group_id: I1CZ2720
      title: Volume 1 of bla ma'i yang tig las gnyis ka'i yang yig kyi rnam par bshad
        pa nyi ma'i snang ba
      total_pages: 250
      order: 1
      base_file: FFFC.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
